language: python

python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "pypy"
  
# command to install dependencies
install:
  - if [[ $TRAVIS_PYTHON_VERSION != '3.5' ]]; then travis_retry pip install typing; fi
  
# command to run tests
script: py.test
